(source "marmalade" "https://marmalade-repo.org/packages/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source melpa)

(depends-on "better-defaults")
(depends-on "dirtree")
(depends-on "enh-ruby-mode")
(depends-on "find-file-in-project")
(depends-on "idle-highlight-mode")
(depends-on "ido-ubiquitous")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "robe")
(depends-on "sass-mode")
(depends-on "scpaste")
(depends-on "skewer-mode")
(depends-on "sly")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "web-mode")
(depends-on "yasnippet")