(set-keyboard-coding-system nil)
(global-linum-mode 1)
(ido-mode 1)
(set-face-attribute 'default nil :height 175)
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(setq ido-enable-flex-matching t)
(setq inhibit-startup-message t
inhibit-startup-echo-area-message t) 
(setq x-select-enable-clipboard t)
(setq gc-cons-threshold 20000000)
(setq-default truncate-lines t)
(defalias 'yes-or-no-p 'y-or-n-p)

(windmove-default-keybindings)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "M-X") 'smex-major-mode-commands)
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)

(define-key global-map (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "C-o") 'dirtree)
(global-set-key (kbd "C-0") 'ace-jump-mode)
(global-set-key (kbd "M-s e") 'sudo-edit)
